development:
  key: 180436381726-q607lfmaht2s92jienfcjulvis8c7qsq.apps.googleusercontent.com
  secret: _7BHnx9RiXROAlqM71XmEpXp
production:
  key: 180436381726-q607lfmaht2s92jienfcjulvis8c7qsq.apps.googleusercontent.com
  secret: _7BHnx9RiXROAlqM71XmEpXp